# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Newt"
  org.opencontainers.image.description: "A tunneling client for Pangolin"
  org.opencontainers.image.source: "https://github.com/socheatsok78/hassio-addons"
  org.opencontainers.image.licenses: "GNU Affero General Public License v3.0 or later"
args:
  NEWT_VERSION: "1.4.4"
  TEMPIO_VERSION: "2021.09.0"
