# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Newt
version: "1.5.0-2"
slug: newt
description: A tunneling client for Pangolin
url: "https://github.com/socheatsok78/hassio-addons/tree/main/newt"
arch:
  - armv7
  - aarch64
  - amd64
init: false
hassio_api: true
host_network: true
options:
  pangolin_endpoint: "https://pangolin.fossorial.io"
  mtu: 1280
  dns: "9.9.9.9"
  accept_clients: false
  ping_interval: 3s
  ping_timeout: 5s
  log_level: INFO
schema:
  pangolin_endpoint: "url?"
  newt_id: "password"
  newt_secret: "password"
  mtu: "int?"
  dns: "str?"
  accept_clients: "bool?"
  ping_interval: "str?"
  ping_timeout: "str?"
  log_level: list(DEBUG|INFO|WARN|ERROR|FATAL)
image: "ghcr.io/socheatsok78/hassio-addon-newt-{arch}"
