# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Newt
version: "1.4.4-1"
slug: newt
description: A tunneling client for Pangolin
url: "https://github.com/socheatsok78/hassio-addons/tree/main/newt"
arch:
  - armv7
  - aarch64
  - amd64
init: false
hassio_api: true
host_network: true
options:
  pangolin_endpoint: "https://pangolin.fossorial.io"
  accept_clients: false
schema:
  pangolin_endpoint: "str?"
  newt_id: "password"
  newt_secret: "password"
  accept_clients: "bool?"
image: "ghcr.io/socheatsok78/hassio-addon-newt-{arch}"
