# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Newt
version: "1.4.4"
slug: newt
description: A tunneling client for Pangolin
url: "https://github.com/socheatsok78/hassio-addons/tree/main/newt"
arch:
  - armv7
  - aarch64
  - amd64
init: false
host_network: true
options:
  pangolin_endpoint: "https://pangolin.fossorial.io"
schema:
  pangolin_endpoint: "str?"
  newt_id: "str?"
  newt_secret: "str?"
image: "ghcr.io/socheatsok78/hassio-addon-newt-{arch}"
